-- Supabase SQL Editor'da çalıştır:
create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  session_id text not null,
  sender text not null check (sender in ('user','support')),
  message text not null,
  created_at timestamptz default now()
);
alter table public.support_messages enable row level security;
create policy "demo insert" on public.support_messages for insert with check (true);
create policy "demo read" on public.support_messages for select using (true);
